facebook:
  app_id: "12312312"
  secret: "adsd12312312"
aws_accesskey_id: "AKIAJ7Q3Y6AWWBRMMD2Q"
aws_secret_access_key: "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"
fog_directory: "crowd-source-complaints"